blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('blog', views.ArticleList.as_view(), name='article_list'),
    path('<int:article_id>/<str:slug>', views.detail, name='detail'),
    path('category/<slug:slug>', views.CategoryList.as_view(), name='category_list'),
    path('author/<slug:username>', views.AuthorList.as_view(), name='author'),
    path('search/', views.SearchList.as_view(), name='search'),
    path('tag/<slug:slug>', views.TagList.as_view(), name='tag_list'),
]

contact_us/urls.py
from django.urls import path
from . import views

app_name = 'contact_us'
urlpatterns = [
    path('contact-us', views.contact_us, name='contact_us'),
    path('about-us', views.about_us, name='about_us'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include('home.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login', views.Login.as_view(), name='login'),
    path('register', views.Register.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    path('', include('blog.urls')),
    path('account/', include('accounts.urls')),
    path('comment/', include('comment.urls')),
    path('', include('contact_us.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('admin.signalsafar/', admin.site.urls),
]

handler404 = 'home.views.handle_404_error'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                      document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'signalsafar'
urlpatterns = [
    path('', views.home, name='home')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.db.models.query_utils import Q
from django.shortcuts import render
from blog.models import Article, Category
# from slider.models import Slider
from slider.models import Slider
from django.db.models import Count, Q
from datetime import datetime, timedelta


def home(request):
    last_month = datetime.today() - timedelta(days=30)
    last_week = datetime.today() - timedelta(days=7)
    context = {
        'articles': Article.objects.published().filter(content_choice='a'),
        'sliders': Slider.objects.all(),
        'last_news': Article.objects.published().filter(content_choice='n')[:4],
        'most_visited_articles_in_last_month': Article.objects.published().annotate(
            count=Count('hits', filter=Q(articlehit__created__gt=last_month))).order_by
                                               ('-count', '-publish')[:8],
        'most_visited_articles_in_last_week': Article.objects.published().annotate(
            count=Count('hits', filter=Q(articlehit__created__gt=last_week))).order_by
                                              ('-count', '-publish')[:8],
    }
    return render(request, 'signalsafar/home.html', context)


def handle_404_error(request, exception):
    return render(request, '404.html', {})

home/templates/partials/category_loop.html
<ul id="dropdown" class="ne-dropdown-menu">
    {% for cat in cat.children.all %}
        <li>
            <a href="{% url 'blog:category_list' cat.slug %}">{{cat.title}}</a>
                {% if cat.children.all %}
                    {% include 'partials/category_loop.html' %}
                {% endif %}
        </li>
    {% endfor %}
</ul>

home/templates/partials/category_navbar.html
<nav id="dropdown">
    <ul>
        <li>
            <a href="{% url 'signalsafar:home' %}">خانه</a>
        </li>
        <li>
            <a href="{% url 'blog:article_list' %}">بلاگ</a>
        </li>
        {% for cat in category %}
            {% if cat.parent == None %}
                <li class="nav-item">
                    <a href="{% url 'blog:category_list' cat.slug %}">{{cat.title}}</a>
                    {% if cat.children.all %}
                    {% include 'partials/category_loop.html' %}
                    {% endif %}
                </li>
            {% endif %}
        {% endfor %}
        <li>
            <a href="{% url 'contact_us:contact_us' %}">تماس با ما</a>
        </li>
        <li>
            <a href="{% url 'contact_us:about_us' %}">درباره ما</a>
        </li>
    </ul>
</nav>                 

home/templates/partials/footer_settings.html
{% load static %}
{% load thumbnail %}
<div class="footer-area-top">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-4 col-md-6 col-sm-12">
                                <div class="footer-box">
                                    <h2 class="title-bold-light title-bar-left text-uppercase">مطالب پربازدید</h2>
                                    <ul class="most-view-post">
                                        {% for article in most_visited_articles_in_last_month %}
                                        <li>
                                            <div class="media">
                                                <a href="post-style-1.html">
                                                    {% thumbnail article.image "100x80" crop="center" as img %}
                                                        <img src="{{ img.url }}" alt="{{ article.image_alt }}" class="img-fluid">
                                                    {% endthumbnail %}
                                                </a>
                                                <div class="media-body">
                                                    <h3 class="title-medium-light size-md mb-10">
                                                        <a href="#">{{ article.title }}</a>
                                                    </h3>
                                                    <div class="post-date-light">
                                                        <ul>
                                                            <li>
                                                                <span>
                                                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                                                </span>11 خرداد 1398</li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                            <div class="col-xl-4 col-lg-3 col-md-6 col-sm-12">
                                <div class="footer-box">
                                    <h2 class="title-bold-light title-bar-left text-uppercase">دسته بندی ها</h2>
                                    <ul class="popular-categories">
                                        {% for category in categories %}
                                        <li>
                                            <a href="{% url 'blog:category_list' category.slug %}">{{ category }}
                                                <span></span>
                                            </a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                            {% comment %} <div class="col-xl-4 col-lg-5 col-md-12 col-sm-12">
                                <div class="footer-box">
                                    <h2 class="title-bold-light title-bar-left text-uppercase">گالری مطالب</h2>
                                    <ul class="post-gallery shine-hover ">
                                        <li>
                                            <a href="gallery-style-1.html">
                                                <figure>
                                                    <img src="img/footer/post4.jpg" alt="post" class="img-fluid">
                                                </figure>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="gallery-style-2.html">
                                                <figure>
                                                    <img src="img/footer/post5.jpg" alt="post" class="img-fluid">
                                                </figure>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="gallery-style-1.html">
                                                <figure>
                                                    <img src="img/footer/post6.jpg" alt="post" class="img-fluid">
                                                </figure>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="gallery-style-2.html">
                                                <figure>
                                                    <img src="img/footer/post7.jpg" alt="post" class="img-fluid">
                                                </figure>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="gallery-style-1.html">
                                                <figure>
                                                    <img src="img/footer/post8.jpg" alt="post" class="img-fluid">
                                                </figure>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="gallery-style-2.html">
                                                <figure>
                                                    <img src="img/footer/post9.jpg" alt="post" class="img-fluid">
                                                </figure>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="gallery-style-1.html">
                                                <figure>
                                                    <img src="img/footer/post10.jpg" alt="post" class="img-fluid">
                                                </figure>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="gallery-style-2.html">
                                                <figure>
                                                    <img src="img/footer/post11.jpg" alt="post" class="img-fluid">
                                                </figure>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="gallery-style-1.html">
                                                <figure>
                                                    <img src="img/footer/post12.jpg" alt="post" class="img-fluid">
                                                </figure>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div> {% endcomment %}
                        </div>
                    </div>
                </div>
                <div class="footer-area-bottom">
                    <div class="container">
                        <div class="row">
                            <div class="col-12 text-center">
                                <a href="{% url 'signalsafar:home' %}" class="footer-logo text-center img-fluid">

                                    <img src="{{ site_settings.footer_logo.url }}" alt="logo" class="img-fluid">
                                </a>
                                <ul class="footer-social">
                                    <li>
                                        <a href="#" title="facebook">
                                            <i class="fa fa-facebook" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" title="twitter">
                                            <i class="fa fa-twitter" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" title="google-plus">
                                            <i class="fa fa-google-plus" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" title="linkedin">
                                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" title="pinterest">
                                            <i class="fa fa-telegram" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" title="rss">
                                            <i class="fa fa-rss" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" title="vimeo">
                                            <i class="fa fa-instagram" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                </ul>
                            <p>تمامی حقوق مادی و معنوی این سایت متعلق به <a href="{% url 'signalsafar:home' %}">سیگنال سفر</a> می باشد و هرگونه کپی برداری غیرقانونی محسوب خواهد شد</p>
                            </div>
                        </div>
                    </div>
                </div>

home/templates/partials/header_settings.html
{% load static %}
{% load base_tags %}
<a href="{% url 'signalsafar:home' %}" class="img-fluid">
    <img src="{{ site_settings.header_logo.url }}" alt="logo" class="img-fluid">
</a>

home/templates/partials/latest_news.html
{% load base_tags %}
{% for news in last_news %}
<li>
    <a href="{{ news.get_absolute_url|truncatewords:20|safe }}">{{ news.title }}</a>
</li>
{% endfor %}

home/templates/partials/nav_logo.html
<link rel="shortcut icon" type="image/x-icon" href="{{ site_settings.fav_logo.url }}">