blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('blog', views.ArticleList.as_view(), name='article_list'),
    path('<int:article_id>/<str:slug>', views.detail, name='detail'),
    path('category/<slug:slug>', views.CategoryList.as_view(), name='category_list'),
    path('author/<slug:username>', views.AuthorList.as_view(), name='author'),
    path('search/', views.SearchList.as_view(), name='search'),
    path('tag/<slug:slug>', views.TagList.as_view(), name='tag_list'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include('home.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login', views.Login.as_view(), name='login'),
    path('register', views.Register.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    path('', include('blog.urls')),
    path('account/', include('accounts.urls')),
    path('comment/', include('comment.urls')),
    path('', include('contact_us.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('admin.signalsafar/', admin.site.urls),
]

handler404 = 'home.views.handle_404_error'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                      document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from extensions.utils import jalali_converter
from accounts.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
# comment
from django.contrib.contenttypes.fields import GenericRelation
from comment.models.comments import Comment
# end comment


class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

    def search(self, query):
        return self.get_queryset()


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


class TagManager(models.Manager):
    def published(self):
        return self.filter(active=True)


class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.CASCADE,
                               related_name='children', verbose_name='زیر دسته')
    title = models.CharField(max_length=200, verbose_name='عنوان')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='آدرس دسته بندی')
    status = models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')
    position = models.IntegerField(verbose_name='پوزیشن')

    objects = CategoryManager()

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['position']

    def __str__(self):
        return self.title


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name='آدرس ip')

    class Meta:
        verbose_name = 'آدرس ip'
        verbose_name_plural = 'آدرس ip ها'

    def __str__(self):
        return self.ip_address


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'منتشر شده'),
    )
    CONTENT_CHOICES = (
        ('a', 'مقاله'),
        ('n', 'خبر'),
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles',
                               verbose_name='نویسنده')
    title = models.CharField(max_length=200, verbose_name='عنوان')
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, verbose_name='آدرس')
    content_choice = models.CharField(max_length=1, choices=CONTENT_CHOICES, default='a', verbose_name='محتوا')
    description = RichTextUploadingField(verbose_name='متن')
    category = models.ManyToManyField(Category, related_name='articles', verbose_name='دسته بندی')
    tags = models.ManyToManyField('Tag', related_name='articles',
                                  verbose_name='تگ ها / برچسب ها')
    image = models.ImageField(upload_to="images", verbose_name='تصویر شاخص مقاله')
    image_alt = models.CharField(max_length=100, blank=True, null=True, verbose_name='متن جایگزین تصویر شاخص')
    publish = models.DateTimeField(default=timezone.now, verbose_name='تاریخ انتشار')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d', verbose_name='وضعیت')
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IPAddress, through="ArticleHit", blank=True, related_name='hits',
                                  verbose_name='بازدید ها')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.id), self.slug])

    def jpublish(self):
        return jalali_converter(self.publish)

    jpublish.short_description = 'تاریخ انتشار'

    def image_tag(self):
        return format_html("<img width=100 height=75 style='border-radius: 5px' src='{}'>".format(self.image.url))

    image_tag.short_description = "عکس مقاله"

    objects = ArticleManager()


class ArticleHit(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    title = models.CharField(max_length=150, verbose_name='عنوان تگ')
    slug = models.SlugField(max_length=150, verbose_name='آدرس تگ')
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False, verbose_name='فعال / غیر فعال')

    class Meta:
        verbose_name = 'تگ / برچسب'
        verbose_name_plural = 'نگ ها / برجسب ها'
        ordering = ['-created']

    def __str__(self):
        return self.title

    objects = TagManager()

blog/views.py
from django.shortcuts import render, get_object_or_404
from accounts.models import User
from django.views.generic import ListView
from .models import Article, Category, Tag
from django.db.models import Q


def detail(request, article_id, slug):
    article = get_object_or_404(Article, id=article_id, slug=slug, status='p')
    context = {
        'article': article,
        'tags': Tag.objects.all(),
        'last_news': Article.objects.published().filter(content_choice='n')[:6],
    }

    ip_address = request.user.ip_address
    if ip_address not in article.hits.all():
        article.hits.add(ip_address)

    return render(request, 'blog/detail.html', context)


class CategoryList(ListView):
    template_name = 'blog/category_list.html'
    paginate_by = 8

    def get_queryset(self):
        global last_news
        last_news = Article.objects.published().filter(content_choice='n')[:5]
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'category': category,
            'last_news': last_news,
        })
        return context


class ArticleList(ListView):
    model = Article
    template_name = 'blog/article_list.html'
    paginate_by = 8

    def get_queryset(self):
        global last_news
        last_news = Article.objects.published().filter(content_choice='n')[:5]
        return Article.objects.published().filter(content_choice='a')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['last_news'] = last_news
        return context


class AuthorList(ListView):
    template_name = 'blog/author_list.html'
    paginate_by = 8

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context


class SearchList(ListView):
    template_name = 'blog/search_list.html'
    paginate_by = 8

    def get_queryset(self):
        global last_news
        last_news = Article.objects.published().filter(content_choice='n')[:5]
        request = self.request
        query = request.GET.get('q')
        if query is not None:
            return Article.objects.filter(
                Q(description__icontains=query) |
                Q(title__icontains=query) |
                Q(tags__title__icontains=query)
            ).distinct()
        return Article.objects.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                'search': self.request.GET.get('q'),
                'last_news': last_news,
            }
        )
        return context


class TagList(ListView):
    template_name = 'blog/tag_list.html'
    paginate_by = 8

    def get_queryset(self):
        global tag
        slug = self.kwargs.get('slug')
        tag = get_object_or_404(Tag.objects.published(), slug=slug)
        return tag.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = tag
        return context

blog/templates/blog/author_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}نویسنده | {{ author.get_full_name }}{% endblock %}
{% block content %}
<!-- Breadcrumb Area Start Here -->
<section class="breadcrumbs-area" style="background-image: url('img/banner/breadcrumbs-banner.jpg');">
    <div class="container">
        <div class="breadcrumbs-content">
            <ul>

                <li>
                    <a href="index.html">نویسنده</a> -
                </li>
                <li>{{ author.get_full_name }}</li>

            </ul>
        </div>
    </div>
</section>
<!-- Breadcrumb Area End Here -->
<!-- Post Style 3 Page Area Start Here -->
<section class="bg-body section-space-less30">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12">
                {% for article in page_obj %}
                <div class="position-relative mb-50-r">
                    <a class="img-opacity-hover mb-30" href="{{ article.get_absolute_url }}">
                        {% thumbnail article.image "450x250" crop="center" as img %}
                            <img src="{{ img.url }}" alt="{{ article.image_alt }}" class="img-fluid width-100">
                        {% endthumbnail %}
                    </a>
                    <div class="topic-box-top-lg">
                        <div class="topic-box-sm color-cod-gray mb-20">{{ article.category.active.last }}</div>
                    </div>
                    <div class="post-date-dark">
                        <ul>
                            <li>
                                <span>توسط</span>
                                <a href="{% url 'blog:author' article.author.username %}">{{ article.author.get_full_name }}</a>
                            </li>
                            <li>
                                <span>
                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                </span>{{ article.jpublish }}
                            </li>
                        </ul>
                    </div>
                    <h3 class="title-medium-dark size-c26">
                        <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                    </h3>
                    <a href="{{ article.get_absolute_url }}" class="btn-ftf-dtp-52">بیشتر بخوانید</a>
                </div>
                {% endfor %}
                <div class="row mb-30">
                    <div class="col-sm-6 col-12">
                        <div class="pagination-btn-wrapper text-center--xs mb15--xs">
                            <ul>
                                {% if page_obj.has_previous %}
                                <li>
                                    <a href="?page={{ page_obj.previous_page_number }}">قبل</a>
                                </li>
                                {% endif %}

                                {% for page in paginator.page_range %}

                                {% if page == page_obj.number %}
                                <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                {% else %}
                                <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endif %}

                                {% endfor %}

                                {% if page_obj.has_next %}
                                <li>
                                    <a href="?page={{ page_obj.next_page_number }}">بعد</a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 col-12">
                        <div class="pagination-result text-left pt-10 text-center--xs">
                            {% for page in paginator.page_range %}

                            {% if page == page_obj.number %}
                            <p class="mb-none">صفحه {{ page }}</p>
                            {% endif %}

                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
            <div class="ne-sidebar sidebar-break-md col-lg-4 col-md-12">

            </div>
        </div>
    </div>
</section>
<!-- Post Style 3 Page Area End Here -->
<!-- Footer Area Start Here -->
<!-- Footer Area End Here -->
<!-- Modal Start-->
{% endblock %}

blog/templates/blog/category_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}دسته بندی | {{ category.title }}{% endblock %}
{% block content %}
<!-- Breadcrumb Area Start Here -->
<section class="breadcrumbs-area" style="background-image: url('img/banner/breadcrumbs-banner.jpg');">
    <div class="container">
        <div class="breadcrumbs-content">
            <ul>

                <li>
                    <p>
                        نتایج دسته بندی : {{ category.title }}
                    <p>
                </li>


            </ul>
        </div>
    </div>
</section>
<!-- Breadcrumb Area End Here -->
<!-- Post Style 3 Page Area Start Here -->
<section class="bg-body section-space-less30">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12">
                {% for article in page_obj %}
                <div class="position-relative mb-50-r">
                    <a class="img-opacity-hover mb-30" href="{{ article.get_absolute_url }}">
                        {% thumbnail article.image "450x250" crop="center" as img %}
                                        <img src="{{ img.url }}" alt="{{ article.thumbnail_alt }}" class="img-fluid width-100">
                                    {% endthumbnail %}
                    </a>
                    <div class="topic-box-top-lg">
                        <div class="topic-box-sm color-cod-gray mb-20">{{ article.category.active.last }}</div>
                    </div>
                    <div class="post-date-dark">
                        <ul>
                            <li>
                                <span>توسط</span>
                                <a href="{% url 'blog:author' article.author %}">{{ article.author }}</a>
                            </li>
                            <li>
                                            <span>
                                                <i class="fa fa-calendar" aria-hidden="true"></i>
                                            </span>{{article.jpublish}}
                            </li>
                        </ul>
                    </div>
                    <h3 class="title-medium-dark size-c26">
                        <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                    </h3>
                    <a href="{{ article.get_absolute_url }}" class="btn-ftf-dtp-52">بیشتر بخوانید</a>
                </div>
                {% endfor %}
                <div class="row mb-30">
                    <div class="col-sm-6 col-12">
                        <div class="pagination-btn-wrapper text-center--xs mb15--xs">
                            <ul>
                                {% if page_obj.has_previous %}
                                <li>
                                    <a href="?page={{ page_obj.previous_page_number }}">قبل</a>
                                </li>
                                {% endif %}

                                {% for page in paginator.page_range %}

                                {% if page == page_obj.number %}
                                <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                {% else %}
                                <li><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endif %}

                                {% endfor %}

                                {% if page_obj.has_next %}
                                <li>
                                    <a href="?page={{ page_obj.next_page_number }}">بعد</a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 col-12">
                        <div class="pagination-result text-left pt-10 text-center--xs">
                            {% for page in paginator.page_range %}

                            {% if page == page_obj.number %}
                            <p class="mb-none">صفحه {{ page }}</p>
                            {% endif %}

                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
            <div class="ne-sidebar sidebar-break-md col-lg-4 col-md-12">
                {% include 'blog/last_news_component.html' %}
            </div>
        </div>
    </div>
</section>
<!-- Post Style 3 Page Area End Here -->
<!-- Footer Area Start Here -->
<!-- Footer Area End Here -->
<!-- Modal Start-->
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load comment_tags %}
{% block title %}{{ article.title }}{% endblock %}
{% block content %}
<!-- News Info List Area End Here -->
<!-- Inner Page Banner Area Start Here -->
<section class="inner-page-banner img-overlay-90">
    <img src="{{ article.image.url }}" alt="{{ article.image_alt }}" class="img-fluid">
    <div class="container">
        <div class="banner-content">
            <div class="topic-box-sm color-cinnabar mb-30 hidden-sm hidden-xs">{{ article.category.last }}</div>
            <div class="inner-banner-title">{{ article.title }}</div>
            <ul class="post-info-light hidden-sm hidden-xs">
                <li>
                    <a href="{% url 'blog:author' article.author.username %}">
                        <span>توسط</span> {{ article.author.get_full_name }}</a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-calendar" aria-hidden="true"></i>{{ article.jpublish }}</a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-eye" aria-hidden="true"></i>{{ article.hits.count }}</a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-comments" aria-hidden="true"></i>{{ article.comments.count }}</a>
                </li>
            </ul>
        </div>
    </div>
</section>
<!-- Inner Page Banner Area End Here -->
<!-- Breadcrumb Area Start Here -->
<!-- Breadcrumb Area End Here -->
<!-- News Details Page Area Start Here -->
<section class="bg-body section-space-less30">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12">
                <div class="news-details-layout3 mb-30">
                    {{ article.description|safe }}
                    <ul class="blog-tags item-inline">
                        <li>دسته بندی ها</li>
                        {% for category in article.category.all %}
                        <li>
                            <a href="{% url 'blog:category_list' category.slug %}">{{ category.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="row no-gutters divider blog-post-slider">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-6">
                            {% if article.get_previous_by_created %}
                                    <a href="{% url 'blog:detail' article.get_previous_by_created.id article.get_previous_by_created.slug %}"
                                       class="prev-article">
                                        <i class="fa fa-angle-right" aria-hidden="true"></i>پست قبلی</a>
                                {% endif %}
                                <h3 class="title-medium-dark pr-50">
                                    {% if article.get_previous_by_created %}
                                        {{ article.get_previous_by_created.title }}
                                    {% else %}
                                        <p class="text-warning">مقاله ای برای نمایش وجود ندارد</p>
                                    {% endif %}
                                </h3>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-6 text-left">
                            {% if article.get_next_by_created %}
                                    <a href="{% url 'blog:detail' article.get_next_by_created.id article.get_next_by_created.slug %}"
                                       class="prev-article">
                                        <i class="fa fa-angle-right" aria-hidden="true"></i>پست بعدی</a>
                                {% endif %}
                                <h3 class="title-medium-dark pr-50">
                                    {% if article.get_next_by_created %}
                                        {{ article.get_next_by_created.title }}
                                    {% else %}
                                        <p class="text-warning">مقاله ای برای نمایش وجود ندارد</p>
                                    {% endif %}
                                </h3>
                        </div>
                    </div>

                    <div>
                        {% if request.user.is_authenticated %}
                        {% render_comments article request %}
                        {% else %}
                            <div class="bg-warning p-35-r mb-50">
                                <p>برای ثبت نظر یا مشاهده نظرات به حساب کاربری خود <a href="{% url 'login' %}">ورود</a> کنید</p>
                                <p>اگر حسابی ندارید از این لینک <a href="{% url 'register' %}">ثبت نام</a> کنید</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="ne-sidebar sidebar-break-md col-lg-4 col-md-12">

                {% include 'blog/last_news_component.html' %}
                <div class="sidebar-box">
                    <div class="topic-border color-cod-gray mb-25">
                        <div class="topic-box-lg color-cod-gray">برچسب ها</div>
                    </div>
                    <ul class="sidebar-tags">
                        {% for tag in article.tags.all %}
                        <li>
                            <a href="{% url 'blog:tag_list' tag.slug %}">{{ tag.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- News Details Page Area End Here -->

{% endblock %}

blog/templates/blog/last_news_component.html
{% load thumbnail %}
<div class="sidebar-box">
    <div class="topic-border color-cod-gray mb-5">
        <div class="topic-box-lg color-cod-gray">اخبار جدید</div>
    </div>
    <div class="row">
        {% for news in last_news %}
        <div class="col-lg-6 col-md-4 col-sm-6 col-6">
            <div class="mt-25 position-relative">
                <div class="topic-box-top-xs">
                    <div class="topic-box-sm color-cod-gray mb-20">{{ news.category.last }}</div>
                </div>
                <a href="{{ news.get_absolute_url }}">
                    {% thumbnail news.image "150x100" crop="center top" as img %}
                        <img src="{{ img.url }}" alt="{{ news.image_alt }}" class="img-fluid m-auto width-100 img-opacity-hover mb-10 display-block">
                    {% endthumbnail %}
                </a>
                <h3 class="title-medium-dark size-md mb-none">
                    <a href="{{ news.get_absolute_url }}">{{ news.title }}</a>
                </h3>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

blog/templates/blog/search_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}جستجو | {{ search }}{% endblock %}
{% block content %}
            <!-- Breadcrumb Area Start Here -->
            <section class="breadcrumbs-area" style="background-image: url('img/banner/breadcrumbs-banner.jpg');">
                <div class="container">
                    <div class="breadcrumbs-content">
                        <ul>

                            <li>
                                <p>
                                نتایج جستجوی : {{ search }}
                                <li>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>
            <!-- Breadcrumb Area End Here -->
            <!-- Post Style 3 Page Area Start Here -->
            <section class="bg-body section-space-less30">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-md-12">
                        {% for article in page_obj %}
                            <div class="position-relative mb-50-r">
								<a class="img-opacity-hover mb-30" href="{{ article.get_absolute_url }}">
                                    {% thumbnail article.image "450x250" crop="center" as img %}
                                        <img src="{{ img.url }}" alt="{{ article.thumbnail_alt }}" class="img-fluid width-100">
                                    {% endthumbnail %}
                                </a>
                                <div class="topic-box-top-lg">
                                    <div class="topic-box-sm color-cod-gray mb-20">{{ article.category.active.last }}</div>
                                </div>
                                <div class="post-date-dark">
                                    <ul>
                                        <li>
                                            <span>توسط</span>
                                            <a href="{% url 'blog:author' article.author %}">{{ article.author.get_full_name }}</a>
                                        </li>
                                        <li>
                                            <span>
                                                <i class="fa fa-calendar" aria-hidden="true"></i>
                                            </span>{{article.jpublish}}</li>
                                    </ul>
                                </div>
                                <h3 class="title-medium-dark size-c26">
                                    <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                                </h3>
                                <a href="{{ article.get_absolute_url }}" class="btn-ftf-dtp-52">بیشتر بخوانید</a>
                            </div>
                            {% empty %}
                            <div class="bg-warning text-center p-35-r mb-50">
                                <p>محتوایی برای نمایش وجود ندارد.</p>
                            </div>
                        {% endfor %}
                            <div class="row mb-30">
                                <div class="col-sm-6 col-12">
                                    <div class="pagination-btn-wrapper text-center--xs mb15--xs">
                                        <ul>
                                            {% if page_obj.has_previous %}
                                                <li>
                                                    <a href="?page={{ page_obj.previous_page_number }}">قبل</a>
                                                </li>
                                            {% endif %}

                                            {% for page in paginator.page_range %}

                                                {% if page == page_obj.number %}
                                                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                                {% else %}
                                                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                                                {% endif %}

                                            {% endfor %}

                                            {% if page_obj.has_next %}
                                                <li>
                                                    <a href="?page={{ page_obj.next_page_number }}">بعد</a>
                                                </li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-sm-6 col-12">
                                    <div class="pagination-result text-left pt-10 text-center--xs">
                                        {% for page in paginator.page_range %}

                                                {% if page == page_obj.number %}
                                        <p class="mb-none">صفحه {{ page }}</p>
                                        {% endif %}

                                            {% endfor %}

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="ne-sidebar sidebar-break-md col-lg-4 col-md-12">
                            {% include 'blog/last_news_component.html' %}
                        </div>
                    </div>
                </div>
            </section>
            <!-- Post Style 3 Page Area End Here -->
            <!-- Footer Area Start Here -->
            <!-- Footer Area End Here -->
            <!-- Modal Start-->
{% endblock %}