accounts/urls.py
from django.urls import path
from .views import Profile, ProfileImage


app_name = 'account'
urlpatterns = [
    # path('', ArticleList.as_view(), name='home'),
    path('profile', Profile.as_view(), name='profile'),
    path('profile-image', ProfileImage.as_view(), name='profile_image'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('blog', views.ArticleList.as_view(), name='article_list'),
    path('<int:article_id>/<str:slug>', views.detail, name='detail'),
    path('category/<slug:slug>', views.CategoryList.as_view(), name='category_list'),
    path('author/<slug:username>', views.AuthorList.as_view(), name='author'),
    path('search/', views.SearchList.as_view(), name='search'),
    path('tag/<slug:slug>', views.TagList.as_view(), name='tag_list'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include('home.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login', views.Login.as_view(), name='login'),
    path('register', views.Register.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    path('', include('blog.urls')),
    path('account/', include('accounts.urls')),
    path('comment/', include('comment.urls')),
    path('', include('contact_us.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('admin.signalsafar/', admin.site.urls),
]

handler404 = 'home.views.handle_404_error'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                      document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html class="no-js" lang="fa">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}سیگنال سفر | خانه{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    {% nav_logo %}
    <!-- Normalize CSS -->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- Main CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- Bootstrap rtl CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-rtl.min.css' %}">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <!-- Font-awesome CSS-->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- Owl Caousel CSS -->
    <link rel="stylesheet" href="{% static 'vendor/OwlCarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/OwlCarousel/owl.theme.default.min.css' %}">
    <!-- Main Menu CSS -->
    <link rel="stylesheet" href="{% static 'css/meanmenu.min.css' %}">
    <!-- Nivo Slider CSS-->
    <link rel="stylesheet" href="{% static 'vendor/slider/css/nivo-slider.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'vendor/slider/css/preview.css' %}" type="text/css" media="screen">
    <!-- Magnific CSS -->
    <link rel="stylesheet" type="{% static 'text/css' %}" href="css/magnific-popup.css">
    <!-- Switch Style CSS -->
    <link rel="stylesheet" href="{% static 'css/hover-min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- For IE -->
    <link rel="stylesheet" type="{% static 'text/css' %}" href="css/ie-only.css">
    <!-- Modernizr Js -->
    <script src="{% static 'js/modernizr-2.8.3.min.js' %}"></script>

</head>

<body>
<!--[if lt IE 8]>
<p class="browserupgrade">شما از یک مرورگر <strong>تاریخ گذشته</strong> استفاده می کنید. لطفا <a
        href="http://browsehappy.com/">مرورگر خود را به روز کنید</a> تا تجربه بهتری داشته باشید.</p>
<![endif]-->
<!-- Add your site or application content here -->
<!-- Preloader Start Here -->
<div id="preloader">
    <div class="text-center middle">
        <div class="lds-ellipsis">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
</div>
<!-- Preloader End Here -->
<div id="wrapper">
    <!-- Header Area Start Here -->
    <header>

        <div id="header-layout2" class="header-style7">
            <div class="header-top-bar">
                <div class="top-bar-top bg-primarytextcolor border-bottom">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-8 col-md-12">
                                <ul class="news-info-list text-center--md">
                                    {% if request.user.is_authenticated %}
                                    <li>
                                        <a href="{% url 'account:profile' %}">
                                            پنل کاربری
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'logout' %}">
                                            خروج
                                        </a>
                                    </li>
                                    <li>
                                        {% else %}
                                        <a href="{% url 'login' %}">
                                            ورود
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'register' %}">
                                            ثبت نام
                                        </a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="main-menu-area bg-body border-bottom" id="sticker">
                <div class="container">
                    <div class="row no-gutters d-flex align-items-center">
                        <div class="col-lg-2 col-md-2 d-none d-lg-block">
                            <div class="logo-area">
                                {% header_settings %}
                            </div>
                        </div>
                        <div class="col-lg-8 d-none d-lg-block position-static min-height-none">
                            <div class="ne-main-menu">

                                {% category_navbar %}


                            </div>
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-2 text-right position-static">
                            <div class="header-action-item on-mobile-fixed">
                                <ul>
                                    <li>
                                        <form class="form-inline ml-5" action="{% url 'blog:search' %}">

                                            <input type="text" value="{{ request.GET.q }}" name="q"
                                                   class="form-control" placeholder="جستجو ..."/>
                                        </form>
                                    </li>
                                    {% comment %}
                                    <li class="d-none d-sm-block d-md-block d-lg-none">
                                        <button type="button" class="login-btn" data-toggle="modal"
                                                data-target="#myModal">
                                            <i class="fa fa-user" aria-hidden="true"></i>ورود
                                        </button>
                                    </li>
                                    <li>
                                        <div id="side-menu-trigger" class="offcanvas-menu-btn offcanvas-btn-repoint">
                                            <a href="#" class="menu-bar">
                                                <span></span>
                                                <span></span>
                                                <span></span>
                                            </a>
                                            <a href="#" class="menu-times close">
                                                <span></span>
                                                <span></span>
                                            </a>
                                        </div>
                                    </li>
                                    {% endcomment %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Area End Here -->
    <!-- News Feed Area Start Here -->
    <section class="container">
        <div class="bg-body-color ml-15 pr-15 mb-10 mt-10">
            <div class="row no-gutters d-flex align-items-center">
                <div class="col-lg-2 col-md-3 col-sm-4 col-5">
                    <div class="topic-box">اخبار داغ</div>
                </div>
                <div class="col-lg-10 col-md-9 col-sm-8 col-7">
                    <div class="feeding-text-light2">
                        <ol id="sample" class="ticker">
                            {% latest_news %}
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- News Feed Area End Here -->
    <!-- Slider Area Start Here -->

    <!-- Slider Area End Here -->
    <!-- Popular Area Start Here -->
    {% block content %} {% endblock %}
    <!-- Category Area End Here -->
    <!-- Footer Area Start Here -->
    <footer>
        {% footer_settings %}
    </footer>
    <!-- Footer Area End Here -->
    <!-- Modal Start-->

    <!-- Offcanvas Menu End -->
</div>
<!-- jquery-->
<script src="{% static 'js/jquery-2.2.4.min.js' %}" type="text/javascript"></script>
<!-- Plugins js -->
<script src="{% static 'js/plugins.js' %}" type="text/javascript"></script>
<!-- Popper js -->
<script src="{% static 'js/popper.js' %}" type="text/javascript"></script>
<!-- Bootstrap js -->
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<!-- WOW JS -->
<script src="{% static 'js/wow.min.js' %}"></script>
<!-- Owl Cauosel JS -->
<script src="{% static 'vendor/OwlCarousel/owl.carousel.min.js' %}" type="text/javascript"></script>
<!-- Meanmenu Js -->
<script src="{% static 'js/jquery.meanmenu.min.js' %}" type="text/javascript"></script>
<!-- Srollup js -->
<script src="{% static 'js/jquery.scrollUp.min.js' %}" type="text/javascript"></script>
<!-- jquery.counterup js -->
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<!-- Nivo slider js -->
<script src="{% static 'vendor/slider/js/jquery.nivo.slider.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/slider/home.js' %}" type="text/javascript"></script>
<!-- Isotope js -->
<script src="{% static 'js/isotope.pkgd.min.js' %}" type="text/javascript"></script>
<!-- Magnific Popup -->
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<!-- Ticker Js -->
<script src="{% static 'js/ticker.js' %}" type="text/javascript"></script>
<!-- Custom Js -->
<script src="{% static 'js/main.js' %}" type="text/javascript"></script>
</body>

</html>